apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-microservice
  labels:
    app: login
spec:
  replicas: 6
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login-microservice
          image: sthanguy/cubechain-login-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          volumeMounts:
            - name: firebase-config
              mountPath: "/usr/login/config/firebase"
              readOnly: true
            - name: signing-secret
              mountPath: "/usr/login/config/jwt"
              readOnly: true
      volumes:
        - name: firebase-config
          secret:
            secretName: firebase-config
        - name: signing-secret
          secret:
            secretName: signing-secret
