apiVersion: v1
kind: Service
metadata:
  name: login-microservice-pod
  labels:
    run: login-microservice-pod
spec:
  ports:
    - port: 3005
      protocol: TCP
  selector:
    app: login-microservice
