apiVersion: v1
kind: Service
metadata:
  name: register-microservice-pod
  labels:
    run: register-microservice-pod
spec:
  ports:
    - port: 3005
      protocol: TCP
  selector:
    app: register-microservice
