apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-microservice
  labels:
    app: register
spec:
  replicas: 6
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: register-microservice
          image: sthanguy/cubechain-register-microservice
          ports:
            - containerPort: 3005
